version: '3'
services:

  db :
    image: mongo:latest
   	ports:
      - 27019:27017
		volumes:
      - vmongo:/data/db
  
 
  

  client:
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - server

  gateway:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - "./gateway/api.conf:/etc/nginx/conf.d/default.conf"
  
volumes:
  vmongo: