version: '3'
services:

  db :
    image: mongo:latest
   	ports:
      - 27019:27017
		volumes:
      - vmongo:/data/db
  
  order_service:
    build: ./ordersservice
    ports:
      - 3001:8080
    depends_on:
      - db

  payement_service:
    build: ./payementservice
    ports:
      - 3002:8080
    depends_on:
      - order_service
    
  product_service:
    build: ./productervice
    ports:
      - 3003:8080
    depends_on:
      - db

  category_service:
    build: ./categoryservice
    ports:
      - 3004:8080
    depends_on:
      - db
  
  users_service:
    build: ./usersservice
    ports:
      - 3005:8080
    depends_on:
      - db

  frontend:
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - server

  gateway:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - "./gateway/api.conf:/etc/nginx/conf.d/default.conf"
  
volumes:
  vmongo: